src/Entity/Reference.php
<?php

namespace App\Entity;

use App\Repository\ReferenceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReferenceRepository::class)
 */
class Reference
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datedebut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datefin;

    /**
     * @ORM\ManyToMany(targetEntity=Utilisateur::class, mappedBy="reference")
     */
    private $utilisateurs;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomClient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contactClient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $AdresseClient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $valeurMission;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $servicesRendus;

    public function __construct()
    {
        $this->utilisateurs = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDatedebut(): ?\DateTimeInterface
    {
        return $this->datedebut;
    }

    public function setDatedebut(\DateTimeInterface $datedebut): self
    {
        $this->datedebut = $datedebut;

        return $this;
    }

    public function getDatefin(): ?\DateTimeInterface
    {
        return $this->datefin;
    }

    public function setDatefin(\DateTimeInterface $datefin): self
    {
        $this->datefin = $datefin;

        return $this;
    }

    /**
     * @return Collection<int, Utilisateur>
     */
    public function getUtilisateurs(): Collection
    {
        return $this->utilisateurs;
    }

    public function addUtilisateur(Utilisateur $utilisateur): self
    {
        if (!$this->utilisateurs->contains($utilisateur)) {
            $this->utilisateurs[] = $utilisateur;
            $utilisateur->addReference($this);
        }

        return $this;
    }

    public function removeUtilisateur(Utilisateur $utilisateur): self
    {
        if ($this->utilisateurs->removeElement($utilisateur)) {
            $utilisateur->removeReference($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->titre ?: '';
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getNomClient(): ?string
    {
        return $this->nomClient;
    }

    public function setNomClient(string $nomClient): self
    {
        $this->nomClient = $nomClient;

        return $this;
    }

    public function getContactClient(): ?string
    {
        return $this->contactClient;
    }

    public function setContactClient(string $contactClient): self
    {
        $this->contactClient = $contactClient;

        return $this;
    }

    public function getAdresseClient(): ?string
    {
        return $this->AdresseClient;
    }

    public function setAdresseClient(string $AdresseClient): self
    {
        $this->AdresseClient = $AdresseClient;

        return $this;
    }

    public function getValeurMission(): ?string
    {
        return $this->valeurMission;
    }

    public function setValeurMission(string $valeurMission): self
    {
        $this->valeurMission = $valeurMission;

        return $this;
    }

    public function getServicesRendus(): ?string
    {
        return $this->servicesRendus;
    }

    public function setServicesRendus(string $servicesRendus): self
    {
        $this->servicesRendus = $servicesRendus;

        return $this;
    }


}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity ;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 * @UniqueEntity(
 *     fields = {"username"},
 *     message="le username existe déjà"
 * )
 * @Vich\Uploadable()
 */
class Utilisateur implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $entreprise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nationalite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $grade;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $departement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\Column(type="integer" , length=255)
     */
    private $Anneeexperience;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $langueParle;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="image_admin", fileNameProperty="image")
     */
    private $imageFile;

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): self
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile)
        {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $roles;

    /**
     * @ORM\OneToMany(targetEntity=ExperienceAcademique::class, mappedBy="utilisateur")
     */
    private $experienceacademiques;

    /**
     * @ORM\OneToMany(targetEntity=ExperienceProfessionnel::class, mappedBy="utilisateur")
     */
    private $experiencesProfessionel;

    /**
     * @ORM\Column(type="integer" , options={"default" : 0})
     */
    private $enabled;

    /**
     * @ORM\ManyToMany(targetEntity=Reference::class, inversedBy="utilisateurs")
     */
    private $reference;

    /**
     * @ORM\OneToMany(targetEntity=DiplomesCertificats::class, mappedBy="utilisateur" ,
     * orphanRemoval = true , cascade = { "persist"})
     */
    private $diplomes;



    public function __construct()
    {
        $this->experienceacademiques = new ArrayCollection();
        $this->experiencesProfessionel = new ArrayCollection();
        $this->reference = new ArrayCollection();
        $this->diplomes = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(string $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    public function getGrade(): ?string
    {
        return $this->grade;
    }

    public function setGrade(string $grade): self
    {
        $this->grade = $grade;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->departement;
    }

    public function setDepartement(string $departement): self
    {
        $this->departement = $departement;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getAnneeexperience()
    {
        return $this->Anneeexperience;
    }

    public function setAnneeexperience(int $Anneeexperience): self
    {
        $this->Anneeexperience = $Anneeexperience;

        return $this;
    }

    public function getLangueParle(): ?string
    {
        return $this->langueParle;
    }

    public function setLangueParle(string $langueParle): self
    {
        $this->langueParle = $langueParle;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRoles()
    {
        return [$this->roles];
    }

    public function setRoles(?string $roles) :self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection<int, ExperienceAcademique>
     */
    public function getExperienceacademiques(): Collection
    {
        return $this->experienceacademiques;
    }

    public function addExperienceacademique(ExperienceAcademique $experienceacademique): self
    {
        if (!$this->experienceacademiques->contains($experienceacademique)) {
            $this->experienceacademiques[] = $experienceacademique;
            $experienceacademique->setUtilisateur($this);
        }

        return $this;
    }

    public function removeExperienceacademique(ExperienceAcademique $experienceacademique): self
    {
        if ($this->experienceacademiques->removeElement($experienceacademique)) {
            // set the owning side to null (unless already changed)
            if ($experienceacademique->getUtilisateur() === $this) {
                $experienceacademique->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ExperienceProfessionnel>
     */
    public function getExperiencesProfessionel(): Collection
    {
        return $this->experiencesProfessionel;
    }

    public function addExperiencesProfessionel(ExperienceProfessionnel $experiencesProfessionel): self
    {
        if (!$this->experiencesProfessionel->contains($experiencesProfessionel)) {
            $this->experiencesProfessionel[] = $experiencesProfessionel;
            $experiencesProfessionel->setUtilisateur($this);
        }

        return $this;
    }

    public function removeExperiencesProfessionel(ExperienceProfessionnel $experiencesProfessionel): self
    {
        if ($this->experiencesProfessionel->removeElement($experiencesProfessionel)) {
            // set the owning side to null (unless already changed)
            if ($experiencesProfessionel->getUtilisateur() === $this) {
                $experiencesProfessionel->setUtilisateur(null);
            }
        }

        return $this;
    }

    public function getEnabled(): ?int
    {
        return $this->enabled;
    }

    public function setEnabled(int $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * @return Collection<int, Reference>
     */
    public function getReference(): Collection
    {
        return $this->reference;
    }

    public function addReference(Reference $reference): self
    {
        if (!$this->reference->contains($reference)) {
            $this->reference[] = $reference;
        }

        return $this;
    }

    public function removeReference(Reference $reference): self
    {
        $this->reference->removeElement($reference);

        return $this;
    }

    public function __toString(): string
    {
        return $this->username ?: '';
    }

    /**
     * @return Collection<int, DiplomesCertificats>
     */
    public function getDiplomes(): Collection
    {
        return $this->diplomes;
    }

    public function addDiplome(DiplomesCertificats $diplome): self
    {
        if (!$this->diplomes->contains($diplome)) {
            $this->diplomes[] = $diplome;
            $diplome->setUtilisateur($this);
        }

src/Form/ConsultantsType.php
<?php

namespace App\Form;

use App\Entity\Utilisateur;
use phpDocumentor\Reflection\Types\True_;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConsultantsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom' , TextType::class)
            ->add('prenom', TextType::class)
            ->add('username',TextType::class)
            ->add('password',PasswordType::class)
            ->add('imageFile',FileType::class,['required'=>false])
            ->add('entreprise')
            ->add('email', EmailType::class)
            ->add('nationalite')
            ->add('grade' , ChoiceType::class , [
                'choices' =>
                    [
                        'Junior' =>'Junior' ,
                        'Senior' => 'Senior',
                        'AssistantManager' => '' ,
                        'Manager' => 'Manager' ,
                        'SeniorManager'=>'SeniorManager',
                        'Directeur'=>'Directeur',
                        'Partner'=>'Partner',
                        'Stagiaire'=>'Stagiaire',
                        'AssociéPartner'=>'AssociéPartner'
                    ]
            ])
            ->add('departement',TextType::class)
            ->add('pays',TextType::class)
            ->add('Anneeexperience',IntegerType::class )
            ->add('langueParle', ChoiceType::class , [
                'choices' =>
                    [
                        'Anglais'=>'Anglais',
                        'Français'=>'Français',
                        'Espagnol'=> 'Espagnol',
                        'Turc'=>'Turc',
                        'Arabe'=>'Arabe',
                        'Italien'=>'Italien',
                        'Allemand'=>'Allemand',
                        'Russe'=>'Russe',
                        'Portugais'=>'Portugais',
                        'Coreen'=>'Coreen',
                        'Japonnais'=>'Japonnais',
                    ]
            ])
            ->add('diplomes', FileType::class , [
                'label'=> " upload Certificat" ,
                'multiple'=>true,
                'mapped'=>false,
                'required'=>false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Utilisateur::class,
        ]);
    }
}

templates/consultants/assign_reference.html.twig
{% extends 'base.html.twig' %}

{% block title %}Assign Reference{% endblock %}

{% block body %}
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Assign /</span> Reference</h4>
        {{ form_start(form) }}
        <div class="row">
            <div class="col-xl-12">
                <!-- HTML5 Inputs -->
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="mb-3 row">
                            {{ form_row(form.reference)}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="mb-3 row">
                <button type="submit" class="btn btn-primary d-grid w-100">Add</button>
            </div>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/consultants/consultantsajax.html.twig
{% for c in consultants %}
    <div class="col-md-6 col-lg-4">
        <div class="card">
            <img class="card-img-top"  src="{{ asset('../assets/img/admin/' ~ c.image)}} ">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-8">
                        <h5 class="card-title">{{ c.grade }}</h5>
                    </div>
                    <div class="col-lg-2">
                        <a href="{{ path('ajouter_expacademique' , {"id" : c.id}) }}" class="btn btn-primary"><i class="bx bx-plus"></i>EA</a>
                    </div>
                    <div class="col-lg-2">
                        <a href="{{ path('ajouter_expprofessionel', {"id" : c.id}) }}" class="btn btn-primary"><i class="bx bx-plus"></i>EP</a>
                    </div>
                </div>
                <p class="card-text"><i class="bx bx-user"></i>nom et prenom : {{ c.nom ~ " "~ c.prenom }}</p>
                <p class="card-text"><i class="bx bx-envelope"></i>email : {{ c.email }}</p>
                <p class="card-text"><i class="bx bx-group"></i>departement : {{ c.departement}}</p>
                <p class="card-text"><i class="bx bx-world"></i>pays : {{ c.pays}}</p>
                <p class="card-text"><i class="bx bx-time"></i>annee d'experience : {{ c.anneeexperience }}</p>
                <p class="card-text"><i class="bx bx-world"></i>Langue : {{ c.langueParle}}</p>
            </div>
            <div class="card-body">
                <a href="{{ path('view_profile' , { 'id' : c.id}) }}" class="btn btn-primary">View Profile</a>
                <a href="{{ path('modifier_consultans' , {"id" : c.id}) }}" class="btn btn-secondary">Edit Profile</a>
                <br><br>
                <a href="{{ path('assignreference' , {'id' : c.id }) }}" class="btn btn-warning">Assign Reference</a>
                <form class="btn"  method="post"  action=" {{ path('supprimer_consultans' , {'id' : c.id})}}" onsubmit="return confirm('Voulez vous supprimer ?')">
                    <input type="hidden" name="_method" value="SUP">
                    <input type="hidden" name="_token" value="">
                    <input type="submit" value="delete" class="btn btn-danger" >
                </form>
            </div>
        </div>
    </div>
{% endfor %}

templates/consultants/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Consultants{% endblock %}

{% block body %}
    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="row">
            <div class="col-lg-4">
                <div class="input-group custom-search-form">
                    <input type="text" id="search" class="form-control" placeholder="Search by nom">
                </div>
            </div>
            <div class="col-lg-4">
                {{ form_start(form) }}
                    {{ form_row(form.refernce)}}
                    <br>
                    <button type="submit" class="btn btn-primary d-grid w-100">rechercher</button>
                {{ form_end(form) }}
            </div>
        </div>
        <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Liste des /</span> Consultants</h4>
        <!-- Content types -->
        <div class="row mb-5" id="all">
            {% include 'consultants/consultantsajax.html.twig' %}
        </div>
        <div class="row mb-5" id="search">
        </div>
    </div>
    <script src="{{ asset('assets/js/jquery.js') }}"></script>
    <script
            src="{{ asset('https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js')}}">
    </script>
    <script>
        $( document ).ready(function() {
            var currentRequest = null;
            $("#search").keyup(function(e){
                /* La variable value va prendre la valeur insérer dans le champ de texte
                afin d’effectuer la recherche */
                var value = $(this).val();
                if(currentRequest != null) {
                    currentRequest.abort();
                }
                /* Ajax est lancé lors du remplissage du champ texte dont l’id est
                « search » pour faire la recherche */
                currentRequest = $.ajax({
                    url : "{{ path('ajaxconsultant')}}",
                    type : 'GET',
                    data: {
                        'searchValue' : value
                    },
                    success : function(retour)
                    {
                        $('#all').html(retour);
                    },
                });
                return false;
            });
        });
    </script>
{% endblock %}

templates/consultants/view_profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Consultants{% endblock %}

{% block body %}
<div class="content-wrapper">
    <!-- Content -->
    <div class="container-xxl flex-grow-1 container-p-y">
        <!-- Content types -->
        <h5 class="pb-1 mb-4">View Profile</h5>

        <div class="row mb-5">
            <div class="col-lg-4">
                <div class="card">
                    <img class="card-img-top"  src="{{ asset('../assets/img/admin/' ~ admin.image)}} ">
                    <div class="card-body">
                        <h5 class="card-title">{{ admin.grade }}</h5>
                        <div class="divider">
                            <div class="divider-text"></div>
                        </div>
                        <p class="card-text text-dark"> references : {{ countref }} </p>
                        <p class="card-text text-dark">Years of experience : {{ admin.anneeexperience }} </p>
                        <div class="divider">
                            <div class="divider-text"></div>
                        </div>
                        <p class="card-text">Entreprise : {{ admin.entreprise }}</p>
                        <div class="divider">
                            <div class="divider-text"></div>
                        </div>
                    </div>
                    <a href="{{ path('modifier_consultans' , {"id" : admin.id}) }}" class="btn btn-secondary">Edit Profile</a>
                    <br>
                    <a href="{{ path('assignreference' , {'id' : admin.id}) }}" class="btn btn-warning">Assign Reference</a>
                    <br>
                    <a href="{{ path('download_consultants' , { 'id' : admin.id }) }}" class="btn btn-danger">Export cv</a>
                    <br>
                    <a href="{{ path('download_reference' , { 'id' : admin.id }) }}" class="btn btn-primary">Export reference</a>
                    <br>
                    <button class="btn btn-success" onclick="generate()">pdf</button>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="card-title">
                            <h1 class='bx bx-briefcase-alt' style="font-size: 50px">Professional Experience</h1>
                        </div>
                        {% for expro in expro  %}
                            <div class="card-text">
                                <p class="card-text"><i class="bx bx-group"></i>entreprise : {{ expro.nomentreprise}}</p>
                                <p class="card-text"><i class="bx bx-time"></i>date debut : {{ expro.datedebut | date('Y-m-d')}}</p>
                                <p class="card-text"><i class="bx bx-time"></i>date fin :  {{ expro.datefin | date('Y-m-d')}}</p>
                                <p class="card-text"><i class="bx bx-world"></i>Lieu : {{ expro.lieu}}</p>
                            </div>
                            <div class="divider">
                                <div class="divider-text"></div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="card-title">
                            <h1 class='bx bx-briefcase-alt' style="font-size: 50px">Professional Academique</h1>
                        </div>
                        {% for expac in expac  %}
                            <div class="card-text">
                                <p class="card-text"><i class="bx bx-group"></i>etablissement : {{ expac.etablissement}}</p>
                                <p class="card-text"><i class="bx bx-time"></i>date debut : {{ expac.datedebut | date('Y-m-d')}}</p>
                                <p class="card-text"><i class="bx bx-time"></i>date fin :  {{ expac.datefin | date('Y-m-d')}}</p>
                            </div>
                            <div class="divider">
                                <div class="divider-text"></div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="card-title">
                            <h1 class='bx bx-briefcase-alt' style="font-size: 50px">Certificats</h1>
                        </div>
                        {% for cer in certificats  %}
                            <div class="card-text">
                                <div class="row mb-5">
                                    <div class="col-lg-12">
                                        <img src="{{ asset('assets/certificats/' ~ cer.name) }}" style="width: 350px" >
                                    </div>
                                </div>
                            </div>
                            <div class="divider">
                                <div class="divider-text"></div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="card-title">
                            <h1 class='bx bx-briefcase-alt' style="font-size: 50px">At Ey Reference</h1>
                        </div>
                        {% for ref in admin.getReference  %}
                            <div class="card-text">
                                <div class="row mb-5">
                                    <div class="col-lg-8">
                                        <p class="card-text"><i class="bx bx-group"></i>titre : {{ ref.titre}}</p>
                                        <p class="card-text"><i class="bx bx-group"></i>description : {{ ref.description}}</p>
                                        <p class="card-text"><i class="bx bx-world"></i>titre : {{ ref.pays}}</p>
                                        <p class="card-text"><i class="bx bx-group"></i>titre : {{ ref.nomClient}}</p>
                                        <p class="card-text"><i class="bx bx-group"></i>titre : {{ ref.contactClient}}</p>
                                        <p class="card-text"><i class="bx bx-group"></i>titre : {{ ref.adresseClient}}</p>
                                        <p class="card-text"><i class="bx bx-group"></i>titre : {{ ref.valeurMission}}</p>
                                        <p class="card-text"><i class="bx bx-group"></i>titre : {{ ref.servicesRendus}}</p>
                                        <p class="card-text"><i class="bx bx-time"></i>date debut : {{ ref.datedebut | date('Y-m-d')}}</p>
                                        <p class="card-text"><i class="bx bx-time"></i>date fin :  {{ ref.datefin | date('Y-m-d')}}</p>
                                    </div>
                                    <div class="col-lg-4">
                                        <a href="{{ path('consultans_references' , {'id' : ref.id}) }}"><i class='bx bxs-zoom-in'></i></a>
                                    </div>
                                </div>
                            </div>
                            <div class="divider">
                                <div class="divider-text"></div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!--/ Content types -->
    </div>
    <!-- / Content -->
</div>
<script src="https://cdn.jsdelivr.net/gh/gitbrent/pptxgenjs@3.11.0/dist/pptxgen.bundle.js"></script>
<script>
    function generate()
    {
        let pptx = new PptxGenJs()
        let slide1 = pptx.addSlide()
        let opts1 = {x:0.0 , y:0.0 , w:'100%',h:1.5,align:center,fontSize:24,color:'white',fill:'black'}
        slide1.addText('Mise en place d’un portail de centralisation'+
        'et de gestion des CV, des références et'+
        'des propositions techniques de l’équipe'+
        'Technology Consulting' , opts1);
        let slide2 = pptx.addSlide()
        slide2.addText('Vos informations :')
        pptx.writeFile()
    }
</script>
{% endblock %}